apiVersion: v1
kind: Namespace
metadata:
  name: oojob
  annotations:
    linkerd.io/inject: enabled
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: build-oojob
  namespace: oojob
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: company
  namespace: oojob
  labels:
    app: company
spec:
  replicas: 3
  selector:
    matchLabels:
      app: company
  template:
    metadata:
      labels:
        app: company
    spec:
      containers:
        - name: company
          image: docker.pkg.github.com/oojob/service-company/company:dev
          imagePullPolicy: "Never"
          resources:
            requests:
              cpu: 100m
          ports:
            - name: grpc
              containerPort: 3005
          env:
            - name: DATABASEURI
              value: "mongodb+srv://oojob:oojobN9@oojob-fxap7.mongodb.net/oojob?retryWrites=true&w=majority"
            - name: PORT
              value: "3005"
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: company
  name: company
  namespace: oojob
spec:
  selector:
    app: company
  ports:
    - name: grpc
      port: 3005
      targetPort: 3005
      protocol: TCP
  clusterIP: None
  # type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: company
  namespace: oojob
  annotations:
    kubernetes.io/ingress.class: "traefik"
    ingress.kubernetes.io/custom-request-headers: l5d-dst-override:web-svc.company.svc.cluster.local:3005
spec:
  rules:
    - host: localhost
      http:
        paths:
          - backend:
              serviceName: company
              servicePort: 3005
