apiVersion: apps/v1
kind: Deployment
metadata:
  name: company
  namespace: oojob
spec:
  replicas: 3
  selector:
    matchLabels:
      app: company
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: company
    spec:
      containers:
      - env:
        - name: DATABASEURI
          value: mongodb+srv://oojob:oojobN9@oojob-fxap7.mongodb.net/oojob?retryWrites=true&w=majority
        - name: PORT
          value: "3005"
        image: docker.pkg.github.com/oojob/service-company/company:dev
        imagePullPolicy: Never
        name: company
        ports:
        - containerPort: 3005
          name: grpc
        resources:
          requests:
            cpu: 100m
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: company
  namespace: oojob
spec:
  selector:
    app: company
  ports:
    - name: grpc
      port: 3005
      targetPort: 3005
      protocol: TCP
  clusterIP: None
---
